language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - nosetests
  - flake8

deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: CiCAhkhxawA2/RjstP+Fg0oCEzIlRpsY8oPY7twLR00F2jKLmjvRwG+MiWoHYOabSzfiEC2gigMLlaYTqs367KenOvdDUySaMdtNDPF89rM47O/Fv1YKYjAAqvxK3EVUfxAJ3mYN1ybv4fLzqu8uInEGSKagziZQhoyRRvYkjagn36bNSuVTDKuhoc2QrKzYyh2CCG6HmNq4IQJKyvsOHdIznQs/HZR75SUeEsFUNyGMLDd+2H19hmaglLSnaW5z5m/21UgTkPu6aY1qP0JL8ob1HaAWgRy4iXrC7x+kauzuXyCU3QrK9vATghNFoy/9n5ILUaS9EANKQOWES/+jFVuQEJn3L6K62ABcB15x1yWG5g4jQ4FmoNNuDluli+d2Q1Bd1CbzaP6xz68tDITo53py9w3blPwYU8anMDsS6CoQvFyXOd2CDTOH/DRC6ziSyzSEnZ03+fRluVesPsEXO1BosbzomwA4P43y726bM7KPJLS/Me3jbqlee6mMOHjeB6nr9GzXSgQFqDFmZu0l75KRspt7unwnXKM9JJwLQme7VL+0lm28vBn1SjF+s46k2nyYazA3RPf6zD6fgVGqgfzHx/WyWF7CN05tJQaF+AgobYxda4UFvtP+1INNGfmJ2+5h//jvamydCHQ45zMdhRSn4YpQgn8mUXttZgtrfC4=
  on:
    tags: true
    python: 3.6
    repo: internap/python-ubersmith-remote-module-server
